# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainbow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.CharField(default='http://jeremyphilemon.github.io/blog/images/me.png', max_length=1000),
            preserve_default=False,
        ),
    ]
